[versions]
agp = "9.3.2"
appcompat = "1.6.1"
material = "1.10.0"
activityKtx = "1.13.0"
constraintlayout = "2.1.4"
recyclerview = "1.1.0"
cardview = "1.0.0"
junit = "4.13.2"
androidxJunit = "1.1.5"
espressoCore = "3.5.1"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

